import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
import App from "@/components/layouts/app";
import Banner from "@/components/banner/banner";
import Language from "@/components/language/language";
import Blog from "@/components/blog/blog";
import AnimationHeader from "@/components/layouts/animationHeader";
import Level from "@/components/level/level";
import Opinions from "@/components/opinions/opinions";
import Staff from "../components/about/staff";

const inter = Inter({ subsets: ["latin"] });

function Home() {
  return (
    <>
      <Head>
        <title>Cool language center</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
          <Banner/>
          <Language/>
          <Opinions/>
          <Blog/>
          <Staff/>
          <Level/>
      </main>
    </>
  );
}

Home.getLayout = function getLayout(page) {
    return (
        <App>
            {page}
        </App>
    )
}

export default Home;
